package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class AddDocumentDataSourceResult {
  private Double datasource_id = null;
  private Double document_id = null;
  private Double job_id = null;
  public Double getDatasource_id() {
    return datasource_id;
  }
  public void setDatasource_id(Double datasource_id) {
    this.datasource_id = datasource_id;
  }

  public Double getDocument_id() {
    return document_id;
  }
  public void setDocument_id(Double document_id) {
    this.document_id = document_id;
  }

  public Double getJob_id() {
    return job_id;
  }
  public void setJob_id(Double job_id) {
    this.job_id = job_id;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddDocumentDataSourceResult {\n");
    sb.append("  datasource_id: ").append(datasource_id).append("\n");
    sb.append("  document_id: ").append(document_id).append("\n");
    sb.append("  job_id: ").append(job_id).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

