package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class AddJobDocumentResult {
  private Double document_id = null;
  public Double getDocument_id() {
    return document_id;
  }
  public void setDocument_id(Double document_id) {
    this.document_id = document_id;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddJobDocumentResult {\n");
    sb.append("  document_id: ").append(document_id).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

