/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class AddQuestionnaireCollectorStyleResult {
  private Double collector_style_id = null;
  private Double collector_id = null;
  private String collector_guid = null;
  public Double getCollector_style_id() {
    return collector_style_id;
  }
  public void setCollector_style_id(Double collector_style_id) {
    this.collector_style_id = collector_style_id;
  }

  public Double getCollector_id() {
    return collector_id;
  }
  public void setCollector_id(Double collector_id) {
    this.collector_id = collector_id;
  }

  public String getCollector_guid() {
    return collector_guid;
  }
  public void setCollector_guid(String collector_guid) {
    this.collector_guid = collector_guid;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddQuestionnaireCollectorStyleResult {\n");
    sb.append("  collector_style_id: ").append(collector_style_id).append("\n");
    sb.append("  collector_id: ").append(collector_id).append("\n");
    sb.append("  collector_guid: ").append(collector_guid).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

