package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class AddQuestionnaireExecutionResult {
  private String execution_guid = null;
  private Double collector_id = null;
  private Double execution_id = null;
  public String getExecution_guid() {
    return execution_guid;
  }
  public void setExecution_guid(String execution_guid) {
    this.execution_guid = execution_guid;
  }

  public Double getCollector_id() {
    return collector_id;
  }
  public void setCollector_id(Double collector_id) {
    this.collector_id = collector_id;
  }

  public Double getExecution_id() {
    return execution_id;
  }
  public void setExecution_id(Double execution_id) {
    this.execution_id = execution_id;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddQuestionnaireExecutionResult {\n");
    sb.append("  execution_guid: ").append(execution_guid).append("\n");
    sb.append("  collector_id: ").append(collector_id).append("\n");
    sb.append("  execution_id: ").append(execution_id).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

