package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class CompareResult {
  private Double job_id = null;
  public Double getJob_id() {
    return job_id;
  }
  public void setJob_id(Double job_id) {
    this.job_id = job_id;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompareResult {\n");
    sb.append("  job_id: ").append(job_id).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

