package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class CreateJobResult {
  private String job_guid = null;
  private Double job_id = null;
  public String getJob_guid() {
    return job_guid;
  }
  public void setJob_guid(String job_guid) {
    this.job_guid = job_guid;
  }

  public Double getJob_id() {
    return job_id;
  }
  public void setJob_id(Double job_id) {
    this.job_id = job_id;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateJobResult {\n");
    sb.append("  job_guid: ").append(job_guid).append("\n");
    sb.append("  job_id: ").append(job_id).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

