package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class DeleteDatasourceResult {
  private Double datasource_id = null;
  public Double getDatasource_id() {
    return datasource_id;
  }
  public void setDatasource_id(Double datasource_id) {
    this.datasource_id = datasource_id;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteDatasourceResult {\n");
    sb.append("  datasource_id: ").append(datasource_id).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

