/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.DeleteAnnotationResult;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class DeleteDocumentAnnotationsResult {
  private List<DeleteAnnotationResult> delete_annotation_results = new ArrayList<DeleteAnnotationResult>();
  public List<DeleteAnnotationResult> getDelete_annotation_results() {
    return delete_annotation_results;
  }
  public void setDelete_annotation_results(List<DeleteAnnotationResult> delete_annotation_results) {
    this.delete_annotation_results = delete_annotation_results;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteDocumentAnnotationsResult {\n");
    sb.append("  delete_annotation_results: ").append(delete_annotation_results).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

