package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class DeleteReplyResult {
  private String annotationGuid = null;
  private String replyGuid = null;
  public String getAnnotationGuid() {
    return annotationGuid;
  }
  public void setAnnotationGuid(String annotationGuid) {
    this.annotationGuid = annotationGuid;
  }

  public String getReplyGuid() {
    return replyGuid;
  }
  public void setReplyGuid(String replyGuid) {
    this.replyGuid = replyGuid;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteReplyResult {\n");
    sb.append("  annotationGuid: ").append(annotationGuid).append("\n");
    sb.append("  replyGuid: ").append(replyGuid).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

