package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.DocumentViewInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class DocumentViewsResult {
  private List<DocumentViewInfo> views = new ArrayList<DocumentViewInfo>();
  public List<DocumentViewInfo> getViews() {
    return views;
  }
  public void setViews(List<DocumentViewInfo> views) {
    this.views = views;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentViewsResult {\n");
    sb.append("  views: ").append(views).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

