package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.DocumentInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class FileMoveResult {
  private DocumentInfo dst_file = null;
  private DocumentInfo src_file = null;
  public DocumentInfo getDst_file() {
    return dst_file;
  }
  public void setDst_file(DocumentInfo dst_file) {
    this.dst_file = dst_file;
  }

  public DocumentInfo getSrc_file() {
    return src_file;
  }
  public void setSrc_file(DocumentInfo src_file) {
    this.src_file = src_file;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileMoveResult {\n");
    sb.append("  dst_file: ").append(dst_file).append("\n");
    sb.append("  src_file: ").append(src_file).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

