package com.groupdocs.sdk.model;

import java.util.*;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class GetDocumentForeignTypesResult {
  private List<String> types = new ArrayList<String>();
  public List<String> getTypes() {
    return types;
  }
  public void setTypes(List<String> types) {
    this.types = types;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDocumentForeignTypesResult {\n");
    sb.append("  types: ").append(types).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

