package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.Datasource;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class GetDatasourceResult {
  private Datasource datasource = null;
  public Datasource getDatasource() {
    return datasource;
  }
  public void setDatasource(Datasource datasource) {
    this.datasource = datasource;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDatasourceResult {\n");
    sb.append("  datasource: ").append(datasource).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

