package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.Datasource;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class GetDatasourcesResult {
  private List<Datasource> datasources = new ArrayList<Datasource>();
  public List<Datasource> getDatasources() {
    return datasources;
  }
  public void setDatasources(List<Datasource> datasources) {
    this.datasources = datasources;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDatasourcesResult {\n");
    sb.append("  datasources: ").append(datasources).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

