package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.QuestionnaireInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class GetDocumentQuestionnairesResult {
  private Double document_id = null;
  private List<QuestionnaireInfo> questionnaires = new ArrayList<QuestionnaireInfo>();
  public Double getDocument_id() {
    return document_id;
  }
  public void setDocument_id(Double document_id) {
    this.document_id = document_id;
  }

  public List<QuestionnaireInfo> getQuestionnaires() {
    return questionnaires;
  }
  public void setQuestionnaires(List<QuestionnaireInfo> questionnaires) {
    this.questionnaires = questionnaires;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDocumentQuestionnairesResult {\n");
    sb.append("  document_id: ").append(document_id).append("\n");
    sb.append("  questionnaires: ").append(questionnaires).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

