package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.JobDocumentsEntry;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class GetJobsDocumentsResult {
  private Integer count = null;
  private List<JobDocumentsEntry> entries = new ArrayList<JobDocumentsEntry>();
  public Integer getCount() {
    return count;
  }
  public void setCount(Integer count) {
    this.count = count;
  }

  public List<JobDocumentsEntry> getEntries() {
    return entries;
  }
  public void setEntries(List<JobDocumentsEntry> entries) {
    this.entries = entries;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetJobsDocumentsResult {\n");
    sb.append("  count: ").append(count).append("\n");
    sb.append("  entries: ").append(entries).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

