package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.QuestionnaireCollectorInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class GetQuestionnaireCollectorResult {
  private QuestionnaireCollectorInfo collector = null;
  public QuestionnaireCollectorInfo getCollector() {
    return collector;
  }
  public void setCollector(QuestionnaireCollectorInfo collector) {
    this.collector = collector;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetQuestionnaireCollectorResult {\n");
    sb.append("  collector: ").append(collector).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

