package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.RoleInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class GetRolesResult {
  private List<RoleInfo> roles = new ArrayList<RoleInfo>();
  public List<RoleInfo> getRoles() {
    return roles;
  }
  public void setRoles(List<RoleInfo> roles) {
    this.roles = roles;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetRolesResult {\n");
    sb.append("  roles: ").append(roles).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

