package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.State;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class GetStatesResult {
  private List<State> states = new ArrayList<State>();
  public List<State> getStates() {
    return states;
  }
  public void setStates(List<State> states) {
    this.states = states;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetStatesResult {\n");
    sb.append("  states: ").append(states).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

