package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.TemplateInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class GetTemplatesResult {
  private List<TemplateInfo> templates = new ArrayList<TemplateInfo>();
  public List<TemplateInfo> getTemplates() {
    return templates;
  }
  public void setTemplates(List<TemplateInfo> templates) {
    this.templates = templates;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTemplatesResult {\n");
    sb.append("  templates: ").append(templates).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

