package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.BillingAddressInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class GetUserSubscriptionPlanResult {
  private Integer id = null;
  private String name = null;
  private BillingAddressInfo billing_address = null;
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  public BillingAddressInfo getBilling_address() {
    return billing_address;
  }
  public void setBilling_address(BillingAddressInfo billing_address) {
    this.billing_address = billing_address;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUserSubscriptionPlanResult {\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  billing_address: ").append(billing_address).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

