package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class MoveAnnotationResult {
  private String annotationGuid = null;
  public String getAnnotationGuid() {
    return annotationGuid;
  }
  public void setAnnotationGuid(String annotationGuid) {
    this.annotationGuid = annotationGuid;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MoveAnnotationResult {\n");
    sb.append("  annotationGuid: ").append(annotationGuid).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

