package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class Range {
  private Integer Length = null;
  private Integer Position = null;
  public Integer getLength() {
    return Length;
  }
  public void setLength(Integer Length) {
    this.Length = Length;
  }

  public Integer getPosition() {
    return Position;
  }
  public void setPosition(Integer Position) {
    this.Position = Position;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Range {\n");
    sb.append("  Length: ").append(Length).append("\n");
    sb.append("  Position: ").append(Position).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

