package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.AnnotationInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SetAnnotationAccessResult {
  private AnnotationInfo annotation = null;
  public AnnotationInfo getAnnotation() {
    return annotation;
  }
  public void setAnnotation(AnnotationInfo annotation) {
    this.annotation = annotation;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetAnnotationAccessResult {\n");
    sb.append("  annotation: ").append(annotation).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

