package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SetUserRolesResult {
  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetUserRolesResult {\n");
    sb.append("}\n");
    return sb.toString();
  }
}

