package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.SharedDocumentInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SharedDocumentsResult {
  private Integer count = null;
  private List<SharedDocumentInfo> documents = new ArrayList<SharedDocumentInfo>();
  public Integer getCount() {
    return count;
  }
  public void setCount(Integer count) {
    this.count = count;
  }

  public List<SharedDocumentInfo> getDocuments() {
    return documents;
  }
  public void setDocuments(List<SharedDocumentInfo> documents) {
    this.documents = documents;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SharedDocumentsResult {\n");
    sb.append("  count: ").append(count).append("\n");
    sb.append("  documents: ").append(documents).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

