package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.SignatureRoleInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureRolesResult {
  private Integer count = null;
  private List<SignatureRoleInfo> roles = new ArrayList<SignatureRoleInfo>();
  public Integer getCount() {
    return count;
  }
  public void setCount(Integer count) {
    this.count = count;
  }

  public List<SignatureRoleInfo> getRoles() {
    return roles;
  }
  public void setRoles(List<SignatureRoleInfo> roles) {
    this.roles = roles;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureRolesResult {\n");
    sb.append("  count: ").append(count).append("\n");
    sb.append("  roles: ").append(roles).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

