package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignaturePredefinedListInfo {
  private String id = null;
  private String values = null;
  private String name = null;
  private String defaultValue = null;
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  public String getValues() {
    return values;
  }
  public void setValues(String values) {
    this.values = values;
  }

  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  public String getDefaultValue() {
    return defaultValue;
  }
  public void setDefaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignaturePredefinedListInfo {\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  values: ").append(values).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  defaultValue: ").append(defaultValue).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

