package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.SignatureSignatureInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureSignatureResult {
  private SignatureSignatureInfo signature = null;
  public SignatureSignatureInfo getSignature() {
    return signature;
  }
  public void setSignature(SignatureSignatureInfo signature) {
    this.signature = signature;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureSignatureResult {\n");
    sb.append("  signature: ").append(signature).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

