package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.SignatureEnvelopeInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureEnvelopesResult {
  private List<SignatureEnvelopeInfo> envelopes = new ArrayList<SignatureEnvelopeInfo>();
  private Integer envelopesCount = null;
  public List<SignatureEnvelopeInfo> getEnvelopes() {
    return envelopes;
  }
  public void setEnvelopes(List<SignatureEnvelopeInfo> envelopes) {
    this.envelopes = envelopes;
  }

  public Integer getEnvelopesCount() {
    return envelopesCount;
  }
  public void setEnvelopesCount(Integer envelopesCount) {
    this.envelopesCount = envelopesCount;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureEnvelopesResult {\n");
    sb.append("  envelopes: ").append(envelopes).append("\n");
    sb.append("  envelopesCount: ").append(envelopesCount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

