package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.SignatureContactInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureContactResult {
  private SignatureContactInfo contact = null;
  public SignatureContactInfo getContact() {
    return contact;
  }
  public void setContact(SignatureContactInfo contact) {
    this.contact = contact;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureContactResult {\n");
    sb.append("  contact: ").append(contact).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

