package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.SignaturePredefinedListInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignaturePredefinedListsResult {
  private List<SignaturePredefinedListInfo> lists = new ArrayList<SignaturePredefinedListInfo>();
  public List<SignaturePredefinedListInfo> getLists() {
    return lists;
  }
  public void setLists(List<SignaturePredefinedListInfo> lists) {
    this.lists = lists;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignaturePredefinedListsResult {\n");
    sb.append("  lists: ").append(lists).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

