package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.SignatureTemplateDocumentInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureTemplateDocumentsResult {
  private String templateId = null;
  private List<SignatureTemplateDocumentInfo> documents = new ArrayList<SignatureTemplateDocumentInfo>();
  public String getTemplateId() {
    return templateId;
  }
  public void setTemplateId(String templateId) {
    this.templateId = templateId;
  }

  public List<SignatureTemplateDocumentInfo> getDocuments() {
    return documents;
  }
  public void setDocuments(List<SignatureTemplateDocumentInfo> documents) {
    this.documents = documents;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureTemplateDocumentsResult {\n");
    sb.append("  templateId: ").append(templateId).append("\n");
    sb.append("  documents: ").append(documents).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

