package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.SignatureEnvelopeDocumentInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureEnvelopeDocumentResult {
  private SignatureEnvelopeDocumentInfo document = null;
  private String envelopeId = null;
  public SignatureEnvelopeDocumentInfo getDocument() {
    return document;
  }
  public void setDocument(SignatureEnvelopeDocumentInfo document) {
    this.document = document;
  }

  public String getEnvelopeId() {
    return envelopeId;
  }
  public void setEnvelopeId(String envelopeId) {
    this.envelopeId = envelopeId;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureEnvelopeDocumentResult {\n");
    sb.append("  document: ").append(document).append("\n");
    sb.append("  envelopeId: ").append(envelopeId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

