package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.SignatureEnvelopeRecipientInfo;
import com.groupdocs.sdk.model.SignatureEnvelopeDocumentInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureEnvelopeResourcesResult {
  private List<String> dates = new ArrayList<String>();
  private List<SignatureEnvelopeRecipientInfo> recipients = new ArrayList<SignatureEnvelopeRecipientInfo>();
  private List<SignatureEnvelopeDocumentInfo> documents = new ArrayList<SignatureEnvelopeDocumentInfo>();
  public List<String> getDates() {
    return dates;
  }
  public void setDates(List<String> dates) {
    this.dates = dates;
  }

  public List<SignatureEnvelopeRecipientInfo> getRecipients() {
    return recipients;
  }
  public void setRecipients(List<SignatureEnvelopeRecipientInfo> recipients) {
    this.recipients = recipients;
  }

  public List<SignatureEnvelopeDocumentInfo> getDocuments() {
    return documents;
  }
  public void setDocuments(List<SignatureEnvelopeDocumentInfo> documents) {
    this.documents = documents;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureEnvelopeResourcesResult {\n");
    sb.append("  dates: ").append(dates).append("\n");
    sb.append("  recipients: ").append(recipients).append("\n");
    sb.append("  documents: ").append(documents).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

