package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.SignatureTemplateFieldInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureTemplateFieldsResult {
  private String templateId = null;
  private List<SignatureTemplateFieldInfo> fields = new ArrayList<SignatureTemplateFieldInfo>();
  public String getTemplateId() {
    return templateId;
  }
  public void setTemplateId(String templateId) {
    this.templateId = templateId;
  }

  public List<SignatureTemplateFieldInfo> getFields() {
    return fields;
  }
  public void setFields(List<SignatureTemplateFieldInfo> fields) {
    this.fields = fields;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureTemplateFieldsResult {\n");
    sb.append("  templateId: ").append(templateId).append("\n");
    sb.append("  fields: ").append(fields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

