package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureFieldSettings {
  private String regularExpression = null;
  private String name = null;
  private Integer graphSizeH = null;
  private String getDataFrom = null;
  private Integer graphSizeW = null;
  public String getRegularExpression() {
    return regularExpression;
  }
  public void setRegularExpression(String regularExpression) {
    this.regularExpression = regularExpression;
  }

  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  public Integer getGraphSizeH() {
    return graphSizeH;
  }
  public void setGraphSizeH(Integer graphSizeH) {
    this.graphSizeH = graphSizeH;
  }

  public String getGetDataFrom() {
    return getDataFrom;
  }
  public void setGetDataFrom(String getDataFrom) {
    this.getDataFrom = getDataFrom;
  }

  public Integer getGraphSizeW() {
    return graphSizeW;
  }
  public void setGraphSizeW(Integer graphSizeW) {
    this.graphSizeW = graphSizeW;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureFieldSettings {\n");
    sb.append("  regularExpression: ").append(regularExpression).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  graphSizeH: ").append(graphSizeH).append("\n");
    sb.append("  getDataFrom: ").append(getDataFrom).append("\n");
    sb.append("  graphSizeW: ").append(graphSizeW).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

