package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.SignatureEnvelopeDocumentInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureEnvelopeDocumentsResult {
  private List<SignatureEnvelopeDocumentInfo> documents = new ArrayList<SignatureEnvelopeDocumentInfo>();
  private String envelopeId = null;
  public List<SignatureEnvelopeDocumentInfo> getDocuments() {
    return documents;
  }
  public void setDocuments(List<SignatureEnvelopeDocumentInfo> documents) {
    this.documents = documents;
  }

  public String getEnvelopeId() {
    return envelopeId;
  }
  public void setEnvelopeId(String envelopeId) {
    this.envelopeId = envelopeId;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureEnvelopeDocumentsResult {\n");
    sb.append("  documents: ").append(documents).append("\n");
    sb.append("  envelopeId: ").append(envelopeId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

