/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureRoleInfo {
  private String id = null;
  private String name = null;
  private Boolean canEdit = null;
  private Boolean canSign = null;
  private Boolean canAnnotate = null;
  private Boolean canDelegate = null;
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  public Boolean getCanEdit() {
    return canEdit;
  }
  public void setCanEdit(Boolean canEdit) {
    this.canEdit = canEdit;
  }

  public Boolean getCanSign() {
    return canSign;
  }
  public void setCanSign(Boolean canSign) {
    this.canSign = canSign;
  }

  public Boolean getCanAnnotate() {
    return canAnnotate;
  }
  public void setCanAnnotate(Boolean canAnnotate) {
    this.canAnnotate = canAnnotate;
  }

  public Boolean getCanDelegate() {
    return canDelegate;
  }
  public void setCanDelegate(Boolean canDelegate) {
    this.canDelegate = canDelegate;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureRoleInfo {\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  canEdit: ").append(canEdit).append("\n");
    sb.append("  canSign: ").append(canSign).append("\n");
    sb.append("  canAnnotate: ").append(canAnnotate).append("\n");
    sb.append("  canDelegate: ").append(canDelegate).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

