package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.SignatureTemplateInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureTemplatesResult {
  private List<SignatureTemplateInfo> templates = new ArrayList<SignatureTemplateInfo>();
  private Integer templatesCount = null;
  public List<SignatureTemplateInfo> getTemplates() {
    return templates;
  }
  public void setTemplates(List<SignatureTemplateInfo> templates) {
    this.templates = templates;
  }

  public Integer getTemplatesCount() {
    return templatesCount;
  }
  public void setTemplatesCount(Integer templatesCount) {
    this.templatesCount = templatesCount;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureTemplatesResult {\n");
    sb.append("  templates: ").append(templates).append("\n");
    sb.append("  templatesCount: ").append(templatesCount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

