/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureFormDocumentSettingsInfo {
  private Integer Order = null;
  private String newDocumentGuid = null;
  public Integer getOrder() {
    return Order;
  }
  public void setOrder(Integer Order) {
    this.Order = Order;
  }

  public String getNewDocumentGuid() {
    return newDocumentGuid;
  }
  public void setNewDocumentGuid(String newDocumentGuid) {
    this.newDocumentGuid = newDocumentGuid;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureFormDocumentSettingsInfo {\n");
    sb.append("  Order: ").append(Order).append("\n");
    sb.append("  newDocumentGuid: ").append(newDocumentGuid).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

