package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.SignatureFormInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureFormsResult {
  private Integer count = null;
  private List<SignatureFormInfo> forms = new ArrayList<SignatureFormInfo>();
  public Integer getCount() {
    return count;
  }
  public void setCount(Integer count) {
    this.count = count;
  }

  public List<SignatureFormInfo> getForms() {
    return forms;
  }
  public void setForms(List<SignatureFormInfo> forms) {
    this.forms = forms;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureFormsResult {\n");
    sb.append("  count: ").append(count).append("\n");
    sb.append("  forms: ").append(forms).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

