/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureFormSettings {
  private Boolean canParticipantDownloadForm = null;
  private String name = null;
  private String fieldsInFinalFileName = null;
  public Boolean getCanParticipantDownloadForm() {
    return canParticipantDownloadForm;
  }
  public void setCanParticipantDownloadForm(Boolean canParticipantDownloadForm) {
    this.canParticipantDownloadForm = canParticipantDownloadForm;
  }

  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  public String getFieldsInFinalFileName() {
    return fieldsInFinalFileName;
  }
  public void setFieldsInFinalFileName(String fieldsInFinalFileName) {
    this.fieldsInFinalFileName = fieldsInFinalFileName;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureFormSettings {\n");
    sb.append("  canParticipantDownloadForm: ").append(canParticipantDownloadForm).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  fieldsInFinalFileName: ").append(fieldsInFinalFileName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

