package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.SignatureEnvelopeRecipientInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureEnvelopeRecipientResult {
  private String envelopeId = null;
  private SignatureEnvelopeRecipientInfo recipient = null;
  public String getEnvelopeId() {
    return envelopeId;
  }
  public void setEnvelopeId(String envelopeId) {
    this.envelopeId = envelopeId;
  }

  public SignatureEnvelopeRecipientInfo getRecipient() {
    return recipient;
  }
  public void setRecipient(SignatureEnvelopeRecipientInfo recipient) {
    this.recipient = recipient;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureEnvelopeRecipientResult {\n");
    sb.append("  envelopeId: ").append(envelopeId).append("\n");
    sb.append("  recipient: ").append(recipient).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

