package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.SignatureTemplateDocumentInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureTemplateDocumentResult {
  private String templateId = null;
  private SignatureTemplateDocumentInfo document = null;
  public String getTemplateId() {
    return templateId;
  }
  public void setTemplateId(String templateId) {
    this.templateId = templateId;
  }

  public SignatureTemplateDocumentInfo getDocument() {
    return document;
  }
  public void setDocument(SignatureTemplateDocumentInfo document) {
    this.document = document;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureTemplateDocumentResult {\n");
    sb.append("  templateId: ").append(templateId).append("\n");
    sb.append("  document: ").append(document).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

