package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.SignatureEnvelopeFieldInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureEnvelopeFieldsResult {
  private String envelopeId = null;
  private List<SignatureEnvelopeFieldInfo> fields = new ArrayList<SignatureEnvelopeFieldInfo>();
  public String getEnvelopeId() {
    return envelopeId;
  }
  public void setEnvelopeId(String envelopeId) {
    this.envelopeId = envelopeId;
  }

  public List<SignatureEnvelopeFieldInfo> getFields() {
    return fields;
  }
  public void setFields(List<SignatureEnvelopeFieldInfo> fields) {
    this.fields = fields;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureEnvelopeFieldsResult {\n");
    sb.append("  envelopeId: ").append(envelopeId).append("\n");
    sb.append("  fields: ").append(fields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

