package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.SignatureFieldInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureFieldResult {
  private SignatureFieldInfo field = null;
  public SignatureFieldInfo getField() {
    return field;
  }
  public void setField(SignatureFieldInfo field) {
    this.field = field;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureFieldResult {\n");
    sb.append("  field: ").append(field).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

