/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.SignatureTemplateFieldLocationInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureTemplateFieldInfo {
  private String regularExpression = null;
  private Integer fieldType = null;
  private Boolean mandatory = null;
  private Integer graphSizeH = null;
  private Double textRows = null;
  private String id = null;
  private String templateId = null;
  private String acceptableValues = null;
  private Double input = null;
  private Double textColumns = null;
  private String recipientId = null;
  private Double order = null;
  private List<SignatureTemplateFieldLocationInfo> locations = new ArrayList<SignatureTemplateFieldLocationInfo>();
  private Double signatureFieldId = null;
  private String name = null;
  private String defaultValue = null;
  private Integer graphSizeW = null;
  private String tooltip = null;
  public String getRegularExpression() {
    return regularExpression;
  }
  public void setRegularExpression(String regularExpression) {
    this.regularExpression = regularExpression;
  }

  public Integer getFieldType() {
    return fieldType;
  }
  public void setFieldType(Integer fieldType) {
    this.fieldType = fieldType;
  }

  public Boolean getMandatory() {
    return mandatory;
  }
  public void setMandatory(Boolean mandatory) {
    this.mandatory = mandatory;
  }

  public Integer getGraphSizeH() {
    return graphSizeH;
  }
  public void setGraphSizeH(Integer graphSizeH) {
    this.graphSizeH = graphSizeH;
  }

  public Double getTextRows() {
    return textRows;
  }
  public void setTextRows(Double textRows) {
    this.textRows = textRows;
  }

  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  public String getTemplateId() {
    return templateId;
  }
  public void setTemplateId(String templateId) {
    this.templateId = templateId;
  }

  public String getAcceptableValues() {
    return acceptableValues;
  }
  public void setAcceptableValues(String acceptableValues) {
    this.acceptableValues = acceptableValues;
  }

  public Double getInput() {
    return input;
  }
  public void setInput(Double input) {
    this.input = input;
  }

  public Double getTextColumns() {
    return textColumns;
  }
  public void setTextColumns(Double textColumns) {
    this.textColumns = textColumns;
  }

  public String getRecipientId() {
    return recipientId;
  }
  public void setRecipientId(String recipientId) {
    this.recipientId = recipientId;
  }

  public Double getOrder() {
    return order;
  }
  public void setOrder(Double order) {
    this.order = order;
  }

  public List<SignatureTemplateFieldLocationInfo> getLocations() {
    return locations;
  }
  public void setLocations(List<SignatureTemplateFieldLocationInfo> locations) {
    this.locations = locations;
  }

  public Double getSignatureFieldId() {
    return signatureFieldId;
  }
  public void setSignatureFieldId(Double signatureFieldId) {
    this.signatureFieldId = signatureFieldId;
  }

  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  public String getDefaultValue() {
    return defaultValue;
  }
  public void setDefaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
  }

  public Integer getGraphSizeW() {
    return graphSizeW;
  }
  public void setGraphSizeW(Integer graphSizeW) {
    this.graphSizeW = graphSizeW;
  }

  public String getTooltip() {
    return tooltip;
  }
  public void setTooltip(String tooltip) {
    this.tooltip = tooltip;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureTemplateFieldInfo {\n");
    sb.append("  regularExpression: ").append(regularExpression).append("\n");
    sb.append("  fieldType: ").append(fieldType).append("\n");
    sb.append("  mandatory: ").append(mandatory).append("\n");
    sb.append("  graphSizeH: ").append(graphSizeH).append("\n");
    sb.append("  textRows: ").append(textRows).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  templateId: ").append(templateId).append("\n");
    sb.append("  acceptableValues: ").append(acceptableValues).append("\n");
    sb.append("  input: ").append(input).append("\n");
    sb.append("  textColumns: ").append(textColumns).append("\n");
    sb.append("  recipientId: ").append(recipientId).append("\n");
    sb.append("  order: ").append(order).append("\n");
    sb.append("  locations: ").append(locations).append("\n");
    sb.append("  signatureFieldId: ").append(signatureFieldId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  defaultValue: ").append(defaultValue).append("\n");
    sb.append("  graphSizeW: ").append(graphSizeW).append("\n");
    sb.append("  tooltip: ").append(tooltip).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

