/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class TemplateEditorFieldStyle {
  private String fontName = null;
  private Integer fontSize = null;
  private String color = null;
  private String backgroundColor = null;
  private Integer borderWidth = null;
  private String borderColor = null;
  private String textAlignment = null;
  public String getFontName() {
    return fontName;
  }
  public void setFontName(String fontName) {
    this.fontName = fontName;
  }

  public Integer getFontSize() {
    return fontSize;
  }
  public void setFontSize(Integer fontSize) {
    this.fontSize = fontSize;
  }

  public String getColor() {
    return color;
  }
  public void setColor(String color) {
    this.color = color;
  }

  public String getBackgroundColor() {
    return backgroundColor;
  }
  public void setBackgroundColor(String backgroundColor) {
    this.backgroundColor = backgroundColor;
  }

  public Integer getBorderWidth() {
    return borderWidth;
  }
  public void setBorderWidth(Integer borderWidth) {
    this.borderWidth = borderWidth;
  }

  public String getBorderColor() {
    return borderColor;
  }
  public void setBorderColor(String borderColor) {
    this.borderColor = borderColor;
  }

  public String getTextAlignment() {
    return textAlignment;
  }
  public void setTextAlignment(String textAlignment) {
    this.textAlignment = textAlignment;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateEditorFieldStyle {\n");
    sb.append("  fontName: ").append(fontName).append("\n");
    sb.append("  fontSize: ").append(fontSize).append("\n");
    sb.append("  color: ").append(color).append("\n");
    sb.append("  backgroundColor: ").append(backgroundColor).append("\n");
    sb.append("  borderWidth: ").append(borderWidth).append("\n");
    sb.append("  borderColor: ").append(borderColor).append("\n");
    sb.append("  textAlignment: ").append(textAlignment).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

