package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class UpdateUserResult {
  private String user_guid = null;
  public String getUser_guid() {
    return user_guid;
  }
  public void setUser_guid(String user_guid) {
    this.user_guid = user_guid;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateUserResult {\n");
    sb.append("  user_guid: ").append(user_guid).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

