package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class UpdateQuestionnaireResult {
  private Double questionnaire_id = null;
  public Double getQuestionnaire_id() {
    return questionnaire_id;
  }
  public void setQuestionnaire_id(Double questionnaire_id) {
    this.questionnaire_id = questionnaire_id;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateQuestionnaireResult {\n");
    sb.append("  questionnaire_id: ").append(questionnaire_id).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

