package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class UserPasswordInfo {
  private String reset_token = null;
  private String old_pswd_salt = null;
  private String new_pswd_salt = null;
  public String getReset_token() {
    return reset_token;
  }
  public void setReset_token(String reset_token) {
    this.reset_token = reset_token;
  }

  public String getOld_pswd_salt() {
    return old_pswd_salt;
  }
  public void setOld_pswd_salt(String old_pswd_salt) {
    this.old_pswd_salt = old_pswd_salt;
  }

  public String getNew_pswd_salt() {
    return new_pswd_salt;
  }
  public void setNew_pswd_salt(String new_pswd_salt) {
    this.new_pswd_salt = new_pswd_salt;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserPasswordInfo {\n");
    sb.append("  reset_token: ").append(reset_token).append("\n");
    sb.append("  old_pswd_salt: ").append(old_pswd_salt).append("\n");
    sb.append("  new_pswd_salt: ").append(new_pswd_salt).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

