/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class AsyncAsyncInputFilesInput extends Object {


    /**
     * User GUID
     */
	 private String userId ;

    /**
     * File GUID
     */
	 private String fileId ;

    /**
     * Target type
     */
	 private String targetType ;

    /**
     * Email results
     */
	 private String emailResults ;

    /**
     * Description
     */
	 private String description ;

    /**
     * Print
     */
	 private String printScript ;


	/**
	 * User GUID
	 * 
	 * 
	 */
	 public String getUserId() {
	 	return userId;
	 }  
	 
	 public void setUserId(String  userId) {
	 	this.userId = userId;
	 }

	/**
	 * File GUID
	 * 
	 * 
	 */
	 public String getFileId() {
	 	return fileId;
	 }  
	 
	 public void setFileId(String  fileId) {
	 	this.fileId = fileId;
	 }

	/**
	 * Target type
	 * 
	 * 
	 */
	 public String getTargetType() {
	 	return targetType;
	 }  
	 
	 public void setTargetType(String  targetType) {
	 	this.targetType = targetType;
	 }

	/**
	 * Email results
	 * 
	 * 
	 */
	 public String getEmailResults() {
	 	return emailResults;
	 }  
	 
	 public void setEmailResults(String  emailResults) {
	 	this.emailResults = emailResults;
	 }

	/**
	 * Description
	 * 
	 * 
	 */
	 public String getDescription() {
	 	return description;
	 }  
	 
	 public void setDescription(String  description) {
	 	this.description = description;
	 }

	/**
	 * Print
	 * 
	 * 
	 */
	 public String getPrintScript() {
	 	return printScript;
	 }  
	 
	 public void setPrintScript(String  printScript) {
	 	this.printScript = printScript;
	 }


}