/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;

import java.util.List;
import java.util.ArrayList;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class Datasource extends Object {


    /**
     * 
     */
	 private Double id ;

    /**
     * 
     */
	 private Long modified_on ;

    /**
     * 
     */
	 private Long created_on ;

    /**
     * 
     */
	 private Double questionnaire_id ;

    /**
     * 
     */
	 private String descr ;

    /**
     * 
     */
	 private List<DatasourceField> fields  =  new ArrayList<DatasourceField>();


	/**
	 * 
	 * 
	 * 
	 */
	 public Double getId() {
	 	return id;
	 }  
	 
	 public void setId(Double  id) {
	 	this.id = id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Long getModified_on() {
	 	return modified_on;
	 }  
	 
	 public void setModified_on(Long  modified_on) {
	 	this.modified_on = modified_on;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Long getCreated_on() {
	 	return created_on;
	 }  
	 
	 public void setCreated_on(Long  created_on) {
	 	this.created_on = created_on;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getQuestionnaire_id() {
	 	return questionnaire_id;
	 }  
	 
	 public void setQuestionnaire_id(Double  questionnaire_id) {
	 	this.questionnaire_id = questionnaire_id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getDescr() {
	 	return descr;
	 }  
	 
	 public void setDescr(String  descr) {
	 	this.descr = descr;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<DatasourceField> getFields() {
	 	return fields;
	 }  
	 
	 public void setFields(List<DatasourceField>  fields) {
	 	this.fields = fields;
	 }


}