/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class DocumentInfo extends Object {


    /**
     * 
     */
	 private String guid ;

    /**
     * 
     */
	 private Double id ;

    /**
     * 
     */
	 private String name ;

    /**
     * 
     */
	 private String access ;

    /**
     * 
     */
	 private String type ;

    /**
     * 
     */
	 private String url ;

    /**
     * 
     */
	 private String file_type ;

    /**
     * 
     */
	 private Long size ;

    /**
     * 
     */
	 private Integer version ;


	/**
	 * 
	 * 
	 * 
	 */
	 public String getGuid() {
	 	return guid;
	 }  
	 
	 public void setGuid(String  guid) {
	 	this.guid = guid;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getId() {
	 	return id;
	 }  
	 
	 public void setId(Double  id) {
	 	this.id = id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getName() {
	 	return name;
	 }  
	 
	 public void setName(String  name) {
	 	this.name = name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getAccess() {
	 	return access;
	 }  
	 
	 public void setAccess(String  access) {
	 	this.access = access;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getType() {
	 	return type;
	 }  
	 
	 public void setType(String  type) {
	 	this.type = type;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getUrl() {
	 	return url;
	 }  
	 
	 public void setUrl(String  url) {
	 	this.url = url;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getFile_type() {
	 	return file_type;
	 }  
	 
	 public void setFile_type(String  file_type) {
	 	this.file_type = file_type;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Long getSize() {
	 	return size;
	 }  
	 
	 public void setSize(Long  size) {
	 	this.size = size;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getVersion() {
	 	return version;
	 }  
	 
	 public void setVersion(Integer  version) {
	 	this.version = version;
	 }


}