/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;

import java.util.List;
import java.util.ArrayList;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class FileSystemFolder extends Object {


    /**
     * 
     */
	 private List<UserInfo> sharers  =  new ArrayList<UserInfo>();

    /**
     * 
     */
	 private String guid ;

    /**
     * 
     */
	 private Double id ;

    /**
     * 
     */
	 private Integer folder_count ;

    /**
     * 
     */
	 private Long modified_on ;

    /**
     * 
     */
	 private Boolean dir ;

    /**
     * 
     */
	 private Long created_on ;

    /**
     * 
     */
	 private String name ;

    /**
     * 
     */
	 private UserInfo owner ;

    /**
     * 
     */
	 private Integer file_count ;

    /**
     * 
     */
	 private String access ;


	/**
	 * 
	 * 
	 * 
	 */
	 public List<UserInfo> getSharers() {
	 	return sharers;
	 }  
	 
	 public void setSharers(List<UserInfo>  sharers) {
	 	this.sharers = sharers;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getGuid() {
	 	return guid;
	 }  
	 
	 public void setGuid(String  guid) {
	 	this.guid = guid;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getId() {
	 	return id;
	 }  
	 
	 public void setId(Double  id) {
	 	this.id = id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getFolder_count() {
	 	return folder_count;
	 }  
	 
	 public void setFolder_count(Integer  folder_count) {
	 	this.folder_count = folder_count;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Long getModified_on() {
	 	return modified_on;
	 }  
	 
	 public void setModified_on(Long  modified_on) {
	 	this.modified_on = modified_on;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getDir() {
	 	return dir;
	 }  
	 
	 public void setDir(Boolean  dir) {
	 	this.dir = dir;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Long getCreated_on() {
	 	return created_on;
	 }  
	 
	 public void setCreated_on(Long  created_on) {
	 	this.created_on = created_on;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getName() {
	 	return name;
	 }  
	 
	 public void setName(String  name) {
	 	this.name = name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public UserInfo getOwner() {
	 	return owner;
	 }  
	 
	 public void setOwner(UserInfo  owner) {
	 	this.owner = owner;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getFile_count() {
	 	return file_count;
	 }  
	 
	 public void setFile_count(Integer  file_count) {
	 	this.file_count = file_count;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getAccess() {
	 	return access;
	 }  
	 
	 public void setAccess(String  access) {
	 	this.access = access;
	 }


}