/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;

import java.util.List;
import java.util.ArrayList;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class GetCollaboratorsResult extends Object {


    /**
     * 
     */
	 private String sessionGuid ;

    /**
     * 
     */
	 private String documentGuid ;

    /**
     * 
     */
	 private List<UserIdentity> collaborators  =  new ArrayList<UserIdentity>();

    /**
     * 
     */
	 private UserIdentity owner ;


	/**
	 * 
	 * 
	 * 
	 */
	 public String getSessionGuid() {
	 	return sessionGuid;
	 }  
	 
	 public void setSessionGuid(String  sessionGuid) {
	 	this.sessionGuid = sessionGuid;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getDocumentGuid() {
	 	return documentGuid;
	 }  
	 
	 public void setDocumentGuid(String  documentGuid) {
	 	this.documentGuid = documentGuid;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<UserIdentity> getCollaborators() {
	 	return collaborators;
	 }  
	 
	 public void setCollaborators(List<UserIdentity>  collaborators) {
	 	this.collaborators = collaborators;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public UserIdentity getOwner() {
	 	return owner;
	 }  
	 
	 public void setOwner(UserIdentity  owner) {
	 	this.owner = owner;
	 }


}