/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;

import java.util.List;
import java.util.ArrayList;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class JobInputDocument extends Object {


    /**
     * 
     */
	 private String status ;

    /**
     * 
     */
	 private String output_formats ;

    /**
     * 
     */
	 private String type ;

    /**
     * 
     */
	 private String access ;

    /**
     * 
     */
	 private String url ;

    /**
     * 
     */
	 private Integer version ;

    /**
     * 
     */
	 private String file_type ;

    /**
     * 
     */
	 private Double id ;

    /**
     * 
     */
	 private String guid ;

    /**
     * 
     */
	 private Long proc_date ;

    /**
     * 
     */
	 private String name ;

    /**
     * 
     */
	 private List<JobOutputDocument> outputs  =  new ArrayList<JobOutputDocument>();

    /**
     * 
     */
	 private String actions ;


	/**
	 * 
	 * 
	 * 
	 */
	 public String getStatus() {
	 	return status;
	 }  
	 
	 public void setStatus(String  status) {
	 	this.status = status;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getOutput_formats() {
	 	return output_formats;
	 }  
	 
	 public void setOutput_formats(String  output_formats) {
	 	this.output_formats = output_formats;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getType() {
	 	return type;
	 }  
	 
	 public void setType(String  type) {
	 	this.type = type;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getAccess() {
	 	return access;
	 }  
	 
	 public void setAccess(String  access) {
	 	this.access = access;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getUrl() {
	 	return url;
	 }  
	 
	 public void setUrl(String  url) {
	 	this.url = url;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getVersion() {
	 	return version;
	 }  
	 
	 public void setVersion(Integer  version) {
	 	this.version = version;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getFile_type() {
	 	return file_type;
	 }  
	 
	 public void setFile_type(String  file_type) {
	 	this.file_type = file_type;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getId() {
	 	return id;
	 }  
	 
	 public void setId(Double  id) {
	 	this.id = id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getGuid() {
	 	return guid;
	 }  
	 
	 public void setGuid(String  guid) {
	 	this.guid = guid;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Long getProc_date() {
	 	return proc_date;
	 }  
	 
	 public void setProc_date(Long  proc_date) {
	 	this.proc_date = proc_date;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getName() {
	 	return name;
	 }  
	 
	 public void setName(String  name) {
	 	this.name = name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<JobOutputDocument> getOutputs() {
	 	return outputs;
	 }  
	 
	 public void setOutputs(List<JobOutputDocument>  outputs) {
	 	this.outputs = outputs;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getActions() {
	 	return actions;
	 }  
	 
	 public void setActions(String  actions) {
	 	this.actions = actions;
	 }


}