/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class SharedSharedInputFilesInput extends Object {


    /**
     * GUID
     */
	 private String guid ;

    /**
     * Page number
     */
	 private String pageNumber ;

    /**
     * Page count
     */
	 private String pageCount ;

    /**
     * Quality
     */
	 private String quality ;

    /**
     * Use Pdf
     */
	 private String usePdf ;


	/**
	 * GUID
	 * 
	 * 
	 */
	 public String getGuid() {
	 	return guid;
	 }  
	 
	 public void setGuid(String  guid) {
	 	this.guid = guid;
	 }

	/**
	 * Page number
	 * 
	 * 
	 */
	 public String getPageNumber() {
	 	return pageNumber;
	 }  
	 
	 public void setPageNumber(String  pageNumber) {
	 	this.pageNumber = pageNumber;
	 }

	/**
	 * Page count
	 * 
	 * 
	 */
	 public String getPageCount() {
	 	return pageCount;
	 }  
	 
	 public void setPageCount(String  pageCount) {
	 	this.pageCount = pageCount;
	 }

	/**
	 * Quality
	 * 
	 * 
	 */
	 public String getQuality() {
	 	return quality;
	 }  
	 
	 public void setQuality(String  quality) {
	 	this.quality = quality;
	 }

	/**
	 * Use Pdf
	 * 
	 * 
	 */
	 public String getUsePdf() {
	 	return usePdf;
	 }  
	 
	 public void setUsePdf(String  usePdf) {
	 	this.usePdf = usePdf;
	 }


}