/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class SignatureFieldInfo extends Object {


    /**
     * 
     */
	 private String fontName ;

    /**
     * 
     */
	 private String fontColor ;

    /**
     * 
     */
	 private String regularExpression ;

    /**
     * 
     */
	 private Integer graphSizeH ;

    /**
     * 
     */
	 private Boolean fontBold ;

    /**
     * 
     */
	 private Double fontSize ;

    /**
     * 
     */
	 private Boolean isSystem ;

    /**
     * 
     */
	 private String id ;

    /**
     * 
     */
	 private Boolean fontItalic ;

    /**
     * 
     */
	 private Boolean fontUnderline ;

    /**
     * 
     */
	 private String name ;

    /**
     * 
     */
	 private String getDataFrom ;

    /**
     * 
     */
	 private Integer graphSizeW ;


	/**
	 * 
	 * 
	 * 
	 */
	 public String getFontName() {
	 	return fontName;
	 }  
	 
	 public void setFontName(String  fontName) {
	 	this.fontName = fontName;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getFontColor() {
	 	return fontColor;
	 }  
	 
	 public void setFontColor(String  fontColor) {
	 	this.fontColor = fontColor;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getRegularExpression() {
	 	return regularExpression;
	 }  
	 
	 public void setRegularExpression(String  regularExpression) {
	 	this.regularExpression = regularExpression;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getGraphSizeH() {
	 	return graphSizeH;
	 }  
	 
	 public void setGraphSizeH(Integer  graphSizeH) {
	 	this.graphSizeH = graphSizeH;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getFontBold() {
	 	return fontBold;
	 }  
	 
	 public void setFontBold(Boolean  fontBold) {
	 	this.fontBold = fontBold;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getFontSize() {
	 	return fontSize;
	 }  
	 
	 public void setFontSize(Double  fontSize) {
	 	this.fontSize = fontSize;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getIsSystem() {
	 	return isSystem;
	 }  
	 
	 public void setIsSystem(Boolean  isSystem) {
	 	this.isSystem = isSystem;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getId() {
	 	return id;
	 }  
	 
	 public void setId(String  id) {
	 	this.id = id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getFontItalic() {
	 	return fontItalic;
	 }  
	 
	 public void setFontItalic(Boolean  fontItalic) {
	 	this.fontItalic = fontItalic;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getFontUnderline() {
	 	return fontUnderline;
	 }  
	 
	 public void setFontUnderline(Boolean  fontUnderline) {
	 	this.fontUnderline = fontUnderline;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getName() {
	 	return name;
	 }  
	 
	 public void setName(String  name) {
	 	this.name = name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getGetDataFrom() {
	 	return getDataFrom;
	 }  
	 
	 public void setGetDataFrom(String  getDataFrom) {
	 	this.getDataFrom = getDataFrom;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getGraphSizeW() {
	 	return graphSizeW;
	 }  
	 
	 public void setGraphSizeW(Integer  graphSizeW) {
	 	this.graphSizeW = graphSizeW;
	 }


}