/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;

import java.util.List;
import java.util.ArrayList;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class SignatureEnvelopeInfo extends Object {


    /**
     * 
     */
	 private String creationDateTime ;

    /**
     * 
     */
	 private Boolean ownerShouldSign ;

    /**
     * 
     */
	 private List<SignatureEnvelopeRecipientInfo> recipients  =  new ArrayList<SignatureEnvelopeRecipientInfo>();

    /**
     * 
     */
	 private Integer status ;

    /**
     * 
     */
	 private Double envelopeExpireTime ;

    /**
     * 
     */
	 private Double ownerId ;

    /**
     * 
     */
	 private Double reminderTime ;

    /**
     * 
     */
	 private String emailSubject ;

    /**
     * 
     */
	 private String statusDateTime ;

    /**
     * 
     */
	 private String id ;

    /**
     * 
     */
	 private Double stepExpireTime ;

    /**
     * 
     */
	 private String emailBody ;

    /**
     * 
     */
	 private Double documentsCount ;

    /**
     * 
     */
	 private Boolean orderedSignature ;

    /**
     * 
     */
	 private Double documentsPages ;

    /**
     * 
     */
	 private String ownerGuid ;

    /**
     * 
     */
	 private String name ;


	/**
	 * 
	 * 
	 * 
	 */
	 public String getCreationDateTime() {
	 	return creationDateTime;
	 }  
	 
	 public void setCreationDateTime(String  creationDateTime) {
	 	this.creationDateTime = creationDateTime;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getOwnerShouldSign() {
	 	return ownerShouldSign;
	 }  
	 
	 public void setOwnerShouldSign(Boolean  ownerShouldSign) {
	 	this.ownerShouldSign = ownerShouldSign;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<SignatureEnvelopeRecipientInfo> getRecipients() {
	 	return recipients;
	 }  
	 
	 public void setRecipients(List<SignatureEnvelopeRecipientInfo>  recipients) {
	 	this.recipients = recipients;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getStatus() {
	 	return status;
	 }  
	 
	 public void setStatus(Integer  status) {
	 	this.status = status;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getEnvelopeExpireTime() {
	 	return envelopeExpireTime;
	 }  
	 
	 public void setEnvelopeExpireTime(Double  envelopeExpireTime) {
	 	this.envelopeExpireTime = envelopeExpireTime;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getOwnerId() {
	 	return ownerId;
	 }  
	 
	 public void setOwnerId(Double  ownerId) {
	 	this.ownerId = ownerId;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getReminderTime() {
	 	return reminderTime;
	 }  
	 
	 public void setReminderTime(Double  reminderTime) {
	 	this.reminderTime = reminderTime;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getEmailSubject() {
	 	return emailSubject;
	 }  
	 
	 public void setEmailSubject(String  emailSubject) {
	 	this.emailSubject = emailSubject;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getStatusDateTime() {
	 	return statusDateTime;
	 }  
	 
	 public void setStatusDateTime(String  statusDateTime) {
	 	this.statusDateTime = statusDateTime;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getId() {
	 	return id;
	 }  
	 
	 public void setId(String  id) {
	 	this.id = id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getStepExpireTime() {
	 	return stepExpireTime;
	 }  
	 
	 public void setStepExpireTime(Double  stepExpireTime) {
	 	this.stepExpireTime = stepExpireTime;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getEmailBody() {
	 	return emailBody;
	 }  
	 
	 public void setEmailBody(String  emailBody) {
	 	this.emailBody = emailBody;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getDocumentsCount() {
	 	return documentsCount;
	 }  
	 
	 public void setDocumentsCount(Double  documentsCount) {
	 	this.documentsCount = documentsCount;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getOrderedSignature() {
	 	return orderedSignature;
	 }  
	 
	 public void setOrderedSignature(Boolean  orderedSignature) {
	 	this.orderedSignature = orderedSignature;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getDocumentsPages() {
	 	return documentsPages;
	 }  
	 
	 public void setDocumentsPages(Double  documentsPages) {
	 	this.documentsPages = documentsPages;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getOwnerGuid() {
	 	return ownerGuid;
	 }  
	 
	 public void setOwnerGuid(String  ownerGuid) {
	 	this.ownerGuid = ownerGuid;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getName() {
	 	return name;
	 }  
	 
	 public void setName(String  name) {
	 	this.name = name;
	 }


}