/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class SignatureTemplateRecipientInfo extends Object {


    /**
     * 
     */
	 private String id ;

    /**
     * 
     */
	 private Integer order ;

    /**
     * 
     */
	 private String nickname ;

    /**
     * 
     */
	 private Double roleId ;


	/**
	 * 
	 * 
	 * 
	 */
	 public String getId() {
	 	return id;
	 }  
	 
	 public void setId(String  id) {
	 	this.id = id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getOrder() {
	 	return order;
	 }  
	 
	 public void setOrder(Integer  order) {
	 	this.order = order;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getNickname() {
	 	return nickname;
	 }  
	 
	 public void setNickname(String  nickname) {
	 	this.nickname = nickname;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getRoleId() {
	 	return roleId;
	 }  
	 
	 public void setRoleId(Double  roleId) {
	 	this.roleId = roleId;
	 }


}