/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class SignatureFieldInfo extends Object {


    /**
     * 
     */
	 private String id ;

    /**
     * 
     */
	 private Double textColumns ;

    /**
     * 
     */
	 private Double input ;

    /**
     * 
     */
	 private String check ;

    /**
     * 
     */
	 private String name ;

    /**
     * 
     */
	 private Integer graphSizeH ;

    /**
     * 
     */
	 private String getDataFrom ;

    /**
     * 
     */
	 private Integer graphSizeW ;

    /**
     * 
     */
	 private Boolean isSystem ;

    /**
     * 
     */
	 private Double textRows ;


	/**
	 * 
	 * 
	 * 
	 */
	 public String getId() {
	 	return id;
	 }  
	 
	 public void setId(String  id) {
	 	this.id = id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getTextColumns() {
	 	return textColumns;
	 }  
	 
	 public void setTextColumns(Double  textColumns) {
	 	this.textColumns = textColumns;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getInput() {
	 	return input;
	 }  
	 
	 public void setInput(Double  input) {
	 	this.input = input;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCheck() {
	 	return check;
	 }  
	 
	 public void setCheck(String  check) {
	 	this.check = check;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getName() {
	 	return name;
	 }  
	 
	 public void setName(String  name) {
	 	this.name = name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getGraphSizeH() {
	 	return graphSizeH;
	 }  
	 
	 public void setGraphSizeH(Integer  graphSizeH) {
	 	this.graphSizeH = graphSizeH;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getGetDataFrom() {
	 	return getDataFrom;
	 }  
	 
	 public void setGetDataFrom(String  getDataFrom) {
	 	this.getDataFrom = getDataFrom;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getGraphSizeW() {
	 	return graphSizeW;
	 }  
	 
	 public void setGraphSizeW(Integer  graphSizeW) {
	 	this.graphSizeW = graphSizeW;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getIsSystem() {
	 	return isSystem;
	 }  
	 
	 public void setIsSystem(Boolean  isSystem) {
	 	this.isSystem = isSystem;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getTextRows() {
	 	return textRows;
	 }  
	 
	 public void setTextRows(Double  textRows) {
	 	this.textRows = textRows;
	 }


}