/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class SignatureTemplateFieldResult extends Object {


    /**
     * 
     */
	 private SignatureTemplateFieldInfo field ;

    /**
     * 
     */
	 private String templateId ;

    /**
     * 
     */
	 private String recipientId ;

    /**
     * 
     */
	 private String documentId ;


	/**
	 * 
	 * 
	 * 
	 */
	 public SignatureTemplateFieldInfo getField() {
	 	return field;
	 }  
	 
	 public void setField(SignatureTemplateFieldInfo  field) {
	 	this.field = field;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getTemplateId() {
	 	return templateId;
	 }  
	 
	 public void setTemplateId(String  templateId) {
	 	this.templateId = templateId;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getRecipientId() {
	 	return recipientId;
	 }  
	 
	 public void setRecipientId(String  recipientId) {
	 	this.recipientId = recipientId;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getDocumentId() {
	 	return documentId;
	 }  
	 
	 public void setDocumentId(String  documentId) {
	 	this.documentId = documentId;
	 }


}