/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class SignatureTemplateFieldLocationSettings extends Object {


    /**
     * 
     */
	 private Double locationHeight ;

    /**
     * 
     */
	 private Boolean fontItalic ;

    /**
     * 
     */
	 private String fontColor ;

    /**
     * 
     */
	 private String fontName ;

    /**
     * 
     */
	 private Boolean forceNewField ;

    /**
     * 
     */
	 private Boolean fontUnderline ;

    /**
     * 
     */
	 private Integer page ;

    /**
     * 
     */
	 private Double locationWidth ;

    /**
     * 
     */
	 private Double locationX ;

    /**
     * 
     */
	 private Boolean fontBold ;

    /**
     * 
     */
	 private Double fontSize ;

    /**
     * 
     */
	 private Double locationY ;


	/**
	 * 
	 * 
	 * 
	 */
	 public Double getLocationHeight() {
	 	return locationHeight;
	 }  
	 
	 public void setLocationHeight(Double  locationHeight) {
	 	this.locationHeight = locationHeight;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getFontItalic() {
	 	return fontItalic;
	 }  
	 
	 public void setFontItalic(Boolean  fontItalic) {
	 	this.fontItalic = fontItalic;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getFontColor() {
	 	return fontColor;
	 }  
	 
	 public void setFontColor(String  fontColor) {
	 	this.fontColor = fontColor;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getFontName() {
	 	return fontName;
	 }  
	 
	 public void setFontName(String  fontName) {
	 	this.fontName = fontName;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getForceNewField() {
	 	return forceNewField;
	 }  
	 
	 public void setForceNewField(Boolean  forceNewField) {
	 	this.forceNewField = forceNewField;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getFontUnderline() {
	 	return fontUnderline;
	 }  
	 
	 public void setFontUnderline(Boolean  fontUnderline) {
	 	this.fontUnderline = fontUnderline;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getPage() {
	 	return page;
	 }  
	 
	 public void setPage(Integer  page) {
	 	this.page = page;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getLocationWidth() {
	 	return locationWidth;
	 }  
	 
	 public void setLocationWidth(Double  locationWidth) {
	 	this.locationWidth = locationWidth;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getLocationX() {
	 	return locationX;
	 }  
	 
	 public void setLocationX(Double  locationX) {
	 	this.locationX = locationX;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getFontBold() {
	 	return fontBold;
	 }  
	 
	 public void setFontBold(Boolean  fontBold) {
	 	this.fontBold = fontBold;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getFontSize() {
	 	return fontSize;
	 }  
	 
	 public void setFontSize(Double  fontSize) {
	 	this.fontSize = fontSize;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getLocationY() {
	 	return locationY;
	 }  
	 
	 public void setLocationY(Double  locationY) {
	 	this.locationY = locationY;
	 }


}