/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;

import java.util.Date;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class SignatureEnvelopeRecipientInfo extends Object {


    /**
     * 
     */
	 private String lastName ;

    /**
     * 
     */
	 private Double delegatedRecipientId ;

    /**
     * 
     */
	 private Integer status ;

    /**
     * 
     */
	 private Date statusDateTime ;

    /**
     * 
     */
	 private String statusMessage ;

    /**
     * 
     */
	 private String id ;

    /**
     * 
     */
	 private String signatureBrowser ;

    /**
     * 
     */
	 private Integer order ;

    /**
     * 
     */
	 private String email ;

    /**
     * 
     */
	 private Double userId ;

    /**
     * 
     */
	 private String signatureLocation ;

    /**
     * 
     */
	 private String signatureFingerprint ;

    /**
     * 
     */
	 private String firstName ;

    /**
     * 
     */
	 private String signatureHost ;

    /**
     * 
     */
	 private String userGuid ;

    /**
     * 
     */
	 private Double roleId ;


	/**
	 * 
	 * 
	 * 
	 */
	 public String getLastName() {
	 	return lastName;
	 }  
	 
	 public void setLastName(String  lastName) {
	 	this.lastName = lastName;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getDelegatedRecipientId() {
	 	return delegatedRecipientId;
	 }  
	 
	 public void setDelegatedRecipientId(Double  delegatedRecipientId) {
	 	this.delegatedRecipientId = delegatedRecipientId;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getStatus() {
	 	return status;
	 }  
	 
	 public void setStatus(Integer  status) {
	 	this.status = status;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Date getStatusDateTime() {
	 	return statusDateTime;
	 }  
	 
	 public void setStatusDateTime(Date  statusDateTime) {
	 	this.statusDateTime = statusDateTime;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getStatusMessage() {
	 	return statusMessage;
	 }  
	 
	 public void setStatusMessage(String  statusMessage) {
	 	this.statusMessage = statusMessage;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getId() {
	 	return id;
	 }  
	 
	 public void setId(String  id) {
	 	this.id = id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getSignatureBrowser() {
	 	return signatureBrowser;
	 }  
	 
	 public void setSignatureBrowser(String  signatureBrowser) {
	 	this.signatureBrowser = signatureBrowser;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getOrder() {
	 	return order;
	 }  
	 
	 public void setOrder(Integer  order) {
	 	this.order = order;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getEmail() {
	 	return email;
	 }  
	 
	 public void setEmail(String  email) {
	 	this.email = email;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getUserId() {
	 	return userId;
	 }  
	 
	 public void setUserId(Double  userId) {
	 	this.userId = userId;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getSignatureLocation() {
	 	return signatureLocation;
	 }  
	 
	 public void setSignatureLocation(String  signatureLocation) {
	 	this.signatureLocation = signatureLocation;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getSignatureFingerprint() {
	 	return signatureFingerprint;
	 }  
	 
	 public void setSignatureFingerprint(String  signatureFingerprint) {
	 	this.signatureFingerprint = signatureFingerprint;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getFirstName() {
	 	return firstName;
	 }  
	 
	 public void setFirstName(String  firstName) {
	 	this.firstName = firstName;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getSignatureHost() {
	 	return signatureHost;
	 }  
	 
	 public void setSignatureHost(String  signatureHost) {
	 	this.signatureHost = signatureHost;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getUserGuid() {
	 	return userGuid;
	 }  
	 
	 public void setUserGuid(String  userGuid) {
	 	this.userGuid = userGuid;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getRoleId() {
	 	return roleId;
	 }  
	 
	 public void setRoleId(Double  roleId) {
	 	this.roleId = roleId;
	 }


}