/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class SignatureEnvelopeSettings extends Object {


    /**
     * 
     */
	 private Integer ownerShouldSign ;

    /**
     * 
     */
	 private Double stepExpireTime ;

    /**
     * 
     */
	 private String emailBody ;

    /**
     * 
     */
	 private Double envelopeExpireTime ;

    /**
     * 
     */
	 private Integer orderedSignature ;

    /**
     * 
     */
	 private Double reminderTime ;

    /**
     * 
     */
	 private String emailSubject ;


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getOwnerShouldSign() {
	 	return ownerShouldSign;
	 }  
	 
	 public void setOwnerShouldSign(Integer  ownerShouldSign) {
	 	this.ownerShouldSign = ownerShouldSign;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getStepExpireTime() {
	 	return stepExpireTime;
	 }  
	 
	 public void setStepExpireTime(Double  stepExpireTime) {
	 	this.stepExpireTime = stepExpireTime;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getEmailBody() {
	 	return emailBody;
	 }  
	 
	 public void setEmailBody(String  emailBody) {
	 	this.emailBody = emailBody;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getEnvelopeExpireTime() {
	 	return envelopeExpireTime;
	 }  
	 
	 public void setEnvelopeExpireTime(Double  envelopeExpireTime) {
	 	this.envelopeExpireTime = envelopeExpireTime;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getOrderedSignature() {
	 	return orderedSignature;
	 }  
	 
	 public void setOrderedSignature(Integer  orderedSignature) {
	 	this.orderedSignature = orderedSignature;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getReminderTime() {
	 	return reminderTime;
	 }  
	 
	 public void setReminderTime(Double  reminderTime) {
	 	this.reminderTime = reminderTime;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getEmailSubject() {
	 	return emailSubject;
	 }  
	 
	 public void setEmailSubject(String  emailSubject) {
	 	this.emailSubject = emailSubject;
	 }


}