/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;

import java.util.Date;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class SignatureSignatureInfo extends Object {


    /**
     * 
     */
	 private String position ;

    /**
     * 
     */
	 private String lastName ;

    /**
     * 
     */
	 private String companyName ;

    /**
     * 
     */
	 private String id ;

    /**
     * 
     */
	 private Double signatureImageFileId ;

    /**
     * 
     */
	 private Double recipientId ;

    /**
     * 
     */
	 private Date createdTimeStamp ;

    /**
     * 
     */
	 private String initialsImageUrl ;

    /**
     * 
     */
	 private String name ;

    /**
     * 
     */
	 private Double initialsImageFileId ;

    /**
     * 
     */
	 private String fullName ;

    /**
     * 
     */
	 private String signatureImageUrl ;

    /**
     * 
     */
	 private String firstName ;

    /**
     * 
     */
	 private String textInitials ;

    /**
     * 
     */
	 private String userGuid ;


	/**
	 * 
	 * 
	 * 
	 */
	 public String getPosition() {
	 	return position;
	 }  
	 
	 public void setPosition(String  position) {
	 	this.position = position;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getLastName() {
	 	return lastName;
	 }  
	 
	 public void setLastName(String  lastName) {
	 	this.lastName = lastName;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCompanyName() {
	 	return companyName;
	 }  
	 
	 public void setCompanyName(String  companyName) {
	 	this.companyName = companyName;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getId() {
	 	return id;
	 }  
	 
	 public void setId(String  id) {
	 	this.id = id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getSignatureImageFileId() {
	 	return signatureImageFileId;
	 }  
	 
	 public void setSignatureImageFileId(Double  signatureImageFileId) {
	 	this.signatureImageFileId = signatureImageFileId;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getRecipientId() {
	 	return recipientId;
	 }  
	 
	 public void setRecipientId(Double  recipientId) {
	 	this.recipientId = recipientId;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Date getCreatedTimeStamp() {
	 	return createdTimeStamp;
	 }  
	 
	 public void setCreatedTimeStamp(Date  createdTimeStamp) {
	 	this.createdTimeStamp = createdTimeStamp;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getInitialsImageUrl() {
	 	return initialsImageUrl;
	 }  
	 
	 public void setInitialsImageUrl(String  initialsImageUrl) {
	 	this.initialsImageUrl = initialsImageUrl;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getName() {
	 	return name;
	 }  
	 
	 public void setName(String  name) {
	 	this.name = name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getInitialsImageFileId() {
	 	return initialsImageFileId;
	 }  
	 
	 public void setInitialsImageFileId(Double  initialsImageFileId) {
	 	this.initialsImageFileId = initialsImageFileId;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getFullName() {
	 	return fullName;
	 }  
	 
	 public void setFullName(String  fullName) {
	 	this.fullName = fullName;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getSignatureImageUrl() {
	 	return signatureImageUrl;
	 }  
	 
	 public void setSignatureImageUrl(String  signatureImageUrl) {
	 	this.signatureImageUrl = signatureImageUrl;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getFirstName() {
	 	return firstName;
	 }  
	 
	 public void setFirstName(String  firstName) {
	 	this.firstName = firstName;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getTextInitials() {
	 	return textInitials;
	 }  
	 
	 public void setTextInitials(String  textInitials) {
	 	this.textInitials = textInitials;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getUserGuid() {
	 	return userGuid;
	 }  
	 
	 public void setUserGuid(String  userGuid) {
	 	this.userGuid = userGuid;
	 }


}