/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.groupdocs.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class StorageStorageInputFoldersInput extends Object {


    /**
     * User GUID
     */
	 private String userId ;

    /**
     * Path
     */
	 private String path ;

    /**
     * Page Index
     */
	 private String pageIndex ;

    /**
     * Page Size
     */
	 private String pageSize ;

    /**
     * Order By
     */
	 private String orderBy ;

    /**
     * Order Asc
     */
	 private String orderAsc ;

    /**
     * Filter
     */
	 private String filter ;

    /**
     * File Types
     */
	 private String fileTypes ;

    /**
     * Indicates whether an extended information should be returned
     */
	 private String extended ;


	/**
	 * User GUID
	 * 
	 * 
	 */
	 public String getUserId() {
	 	return userId;
	 }  
	 
	 public void setUserId(String  userId) {
	 	this.userId = userId;
	 }

	/**
	 * Path
	 * 
	 * 
	 */
	 public String getPath() {
	 	return path;
	 }  
	 
	 public void setPath(String  path) {
	 	this.path = path;
	 }

	/**
	 * Page Index
	 * 
	 * 
	 */
	 public String getPageIndex() {
	 	return pageIndex;
	 }  
	 
	 public void setPageIndex(String  pageIndex) {
	 	this.pageIndex = pageIndex;
	 }

	/**
	 * Page Size
	 * 
	 * 
	 */
	 public String getPageSize() {
	 	return pageSize;
	 }  
	 
	 public void setPageSize(String  pageSize) {
	 	this.pageSize = pageSize;
	 }

	/**
	 * Order By
	 * 
	 * 
	 */
	 public String getOrderBy() {
	 	return orderBy;
	 }  
	 
	 public void setOrderBy(String  orderBy) {
	 	this.orderBy = orderBy;
	 }

	/**
	 * Order Asc
	 * 
	 * 
	 */
	 public String getOrderAsc() {
	 	return orderAsc;
	 }  
	 
	 public void setOrderAsc(String  orderAsc) {
	 	this.orderAsc = orderAsc;
	 }

	/**
	 * Filter
	 * 
	 * 
	 */
	 public String getFilter() {
	 	return filter;
	 }  
	 
	 public void setFilter(String  filter) {
	 	this.filter = filter;
	 }

	/**
	 * File Types
	 * 
	 * 
	 */
	 public String getFileTypes() {
	 	return fileTypes;
	 }  
	 
	 public void setFileTypes(String  fileTypes) {
	 	this.fileTypes = fileTypes;
	 }

	/**
	 * Indicates whether an extended information should be returned
	 * 
	 * 
	 */
	 public String getExtended() {
	 	return extended;
	 }  
	 
	 public void setExtended(String  extended) {
	 	this.extended = extended;
	 }


}